version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Backend service (for containerized deployment)
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - RAG_DATA_DIR=/app/data
      - RAG_PROFILE=balanced
    volumes:
      - backend_data:/app/data
      - ../backend:/app
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - full  # Only start with docker-compose --profile full up

volumes:
  qdrant_data:
    driver: local
  backend_data:
    driver: local

networks:
  default:
    name: rag-network
