services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  # Optional: Backend service (for containerized deployment)
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - RAG_DATA_DIR=/app/data
      - RAG_PROFILE=balanced
      # Use host.docker.internal to reach host's Ollama (macOS/Windows). On Linux, set to http://host.docker.internal:11434 and ensure gateway mapping or expose Ollama.
      - OLLAMA_HOST=http://host.docker.internal:11434
    volumes:
      - backend_data:/app/data
      - ../backend:/app
    depends_on:
      - qdrant
    restart: unless-stopped
    profiles:
      - full  # Only start with docker-compose --profile full up

volumes:
  qdrant_data:
    driver: local
  backend_data:
    driver: local

networks:
  default:
    name: rag-network
